version: 2
updates:
    # PHP Deps
    - package-ecosystem: composer
      directory: "/"
      registries: "*"
      schedule:
          interval: daily
    
    # NodeJS Deps
    - package-ecosystem: npm
      directory: "/"
      registries: "*"
      schedule:
          interval: daily

    # Github Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      commit-message:
          prefix: "[DEPS][GHA]"

    # Docker images
    - package-ecosystem: docker
      directory: "/docker/nodejs"
      registries: "*"
      schedule:
          interval: daily
    - package-ecosystem: docker
      directory: "/docker/php"
      registries: "*"
      schedule:
          interval: daily
