services:
  php:
    build: ./docker/php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  nodejs:
    build: ./docker/nodejs
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    env_file: ./.env

  wordpress:
    build: 
      context: ./docker/wordpress
      args:
        WORDPRESS_VERSION: $WORDPRESS_VERSION
    ports:
      - "8000:80"
    volumes:
      - ./packages/:/var/www/html/wp-content/plugins/
      - wordpress:/var/www/html
    
  wpcli: 
    image: wordpress:cli
    volumes:
      - ./packages/:/var/www/html/wp-content/plugins/
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  githooks:
    build: ./docker/githooks
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks

volumes:
  wordpress: