version: '3.1'

services:
  php:
    build: ./docker/php
    working_dir: /usr/src/app
    volumes: 
      - .:/usr/src/app
  nodejs:
    build: ./docker/nodejs
    working_dir: /usr/src/app
    volumes: 
      - .:/usr/src/app
