FROM wordpress:6.5.3

COPY ./wp-config.php /var/www/html/wp-config.php
COPY ./db.php /var/www/html/wp-content/db.php
COPY ./mu-plugins /var/www/html/wp-content/mu-plugins
COPY ./themes /var/www/html/wp-content/themes
