name: Checkout WP Deps Branch
description: Checkout a branch for the WP Deps update action

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  
outputs:
  pr-head-sha:
    description: 'The SHA of the head of the PR'
    value: ${{ steps.parse-pr-number.outputs.PR_HEAD_SHA }}

# Based on example https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#using-data-from-the-triggering-workflow

runs:
  using: composite
  steps:
    - name: 'Download artifact'
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: ${{ github.event.workflow_run.id }},
          });

          if ( allArtifacts.data.total_count == 0 || allArtifacts.data.artifacts.length == 0 ) {
            throw new Error('No artifacts found');
          }

          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "pr_number"
          })[0];

          if ( !matchArtifact ) {
            throw new Error('No matching artifact found');
          }

          let download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: matchArtifact.id,
            archive_format: 'zip',
          });
          
          require('fs').writeFileSync('pr_number.zip', Buffer.from(download.data));

    - name: Parse PR Number
      shell: bash
      id: parse-pr-number
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
        unzip pr_number.zip
        cat pr_number
        echo "PR_HEAD_SHA=$(gh api repos/${{ github.repository }}/pulls/$(cat pr_number) | jq -r '.head.sha')" >> $GITHUB_OUTPUT
        rm pr_number.zip pr_number

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.parse-pr-number.outputs.PR_HEAD_SHA }}
