name: Update WP Packaes
description: 'Update WP Packages'
inputs: 
  WP_VERSION: 
    description: 'WP Version to update packages for'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs:
  using: composite
  steps:

    # Setup the action
    - name: Clone Repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Install Deps
      shell: bash
      run: npm ci

    # Run the update script
    - name: Update WP Packages
      shell: bash
      run: npm run packages-update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        commit-message: Update WP Packages to ${{ inputs.WP_VERSION }}
        committer: BoxUK WP Robot <developers@boxuk.com>
        author: BoxUK WP Robot <developers@boxuk.com>
        branch: update-wp-deps/${{ inputs.WP_VERSION }}
        delete-branch: true
        title: '[DEPS] Update WP Deps to ${{ inputs.WP_VERSION }}'
        body: |
          This PR updates the WordPress packages to the version that's compatible with the current WP version.
