name: Update WP Packaes
description: 'Update WP Packages'
inputs: 
  WP_VERSION: 
    description: 'WP Version to update packages for'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs:
  using: composite
  steps:

    # Setup the action
    - name: Clone Repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Install Deps
      shell: bash
      run: npm install

    # Run the update script
    - name: Update WP Packages
      shell: bash
      run: npm run packages-update
    
    # Create a PR
    - name: Create Pull Request
      uses: gr2m/create-or-update-pull-request-action@v1
      env: 
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with: 
        title: "[DEPS] Update WP Packages for WP $WP_VERSION"
        body: "This PR updates the WP packages to the latest versions for WP $WP_VERSION"
        branch: "deps/wp-packages/wp-$WP_VERSION"
        author: "BoxUK WordPress Robot<wordpress@boxuk.com>"
        labels: "dependencies"
        github-token: ${{ inputs.GITHUB_TOKEN }}