name: Update WP Packaes
description: 'Update WP Packages'
inputs: 
  WP_VERSION: 
    description: 'WP Version to update packages for'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
runs:
  using: composite
  steps:

    # Setup the action
    - name: Clone Repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 1
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: npm
    - name: Install Deps
      shell: bash
      run: npm ci

    # Run the update script
    - name: Update WP Packages
      shell: bash
      run: npm run packages-update

    # Commit the changes
    - name: Commit changes
      shell: bash
      run: |
          git config --global user.email "developers@boxuk.com"
          git config --global user.name "boxuk-wp-robot"
          git config --global push.autoSetupRemote true
          git checkout -b update-wp-deps/$WP_VERSION
          git add .
          git commit -n -m "[DEPS] Update WordPress packages to $WP_VERSION"
          git push -f

    # Create a PR
    - name: Create PR #if needed
      shell: bash
      run: |
        gh pr create --title "[DEPS] Update WordPress packages to $WP_VERSION" --body "This PR updates the WordPress packages to the version that's compatible with the current WP version." --base main --head update-wp-deps/$WP_VERSION
      continue-on-error: true # If the PR already exists, the action will fail, but we don't want the whole workflow to fail.
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}