name: Mark Check Status
description: Marks a check status for a given PR

inputs:
  status:
    description: 'The status to set'
    required: true
    default: 'pending'
  pr-head-sha:
    description: 'The SHA of the head of the PR'

runs:
  using: composite
  steps:
    - name: Set Check Status
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api repos/${{ github.repository }}/statuses/${{ inputs.pr-head-sha }} \
          -f state=${{ inputs.status }} \
          -f target_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          -f context="${{ github.workflow }}" \
          -f description="${{ github.workflow }}"
