name: All Checks

on:
  pull_request:
  workflow_run:
    workflows: ["Update WP Deps"]
    types:
      - completed

jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Checkout
        uses: boxuk/wp-checkout-deps-auto-update@main
        id: checkout-deps
        if: github.event_name == 'workflow_run'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark Check Outcome
        if: github.event_name == 'workflow_run'
        uses: boxuk/mark-check-status@main
        with: 
          status: ${{ job.status }}
          pr-head-sha: ${{ steps.checkout-deps.outputs.pr-head-sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
