name: Publish Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'packages/**/*.md'
      - 'readme.md'

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-dotnet@v4
        name: Setup
        with:
          dotnet-version: 7.0.x
      - uses: retypeapp/action-build@latest
        name: Build
      - uses: retypeapp/action-github-pages@latest
        name: Publish
        with:
          update-branch: true
