name: "Packages Split"

on:
  push:
    branches:
      - main
    # tags: # Todo - handle tags, ie publishing a new version from the mono-repo to all the sub-repos. 
      # - "*"

permissions:
  contents: write
  pull-requests: write
  checks: write
  issues: write

jobs:
  packages_split:
    runs-on: ubuntu-latest
    name: Publish Package ${{ matrix.packages.local_path }}

    strategy:
      fail-fast: false
      matrix:
        packages:
          - local_path: "editor-tools"
            target_repo: "wp-editor-tools"
          - local_path: "iconography"
            target_repo: "wp-iconography"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Build Packages
        run: npm run build
      - name: Remove `/packages/*/build` from gitignore
        run: |
          sed -i '/\/packages\/\*\/build/d' .gitignore

      - name: Install Splitsh
        shell: bash
        run: go install github.com/splitsh/lite@latest
      - name: Split MonoRepo
        shell: bash
        run: |
          git remote add ${{ matrix.packages.target_repo }} git@github.com:boxuk/${{ matrix.packages.target_repo }}.git || true
          SHA1=`splitsh-lite --prefix=pacakges/${{ matrix.packages.local_path }}`
          git push ${{ matrix.packages.target_repo }} "$SHA1:refs/heads/main" -f
