name: "Packages Split"

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        packages:
          - local_path: "editor-tools"
            target_repo: "wp-editor-tools"
          - local_path: "iconography"
            target_repo: "wp-iconography"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: npm install
      - name: Build Packages
        run: npm run build
      - name: Remove `build` from gitignore
        run: sed -i '/build/d' .gitignore
      

      # no tag
      - name: Split Monorepo
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@2.3"
        with:
          package_directory: "packages/${{ matrix.packages.local_path }}"
          repository_organization: "boxuk"
          repository_name: "${{ matrix.packages.target_repo }}"
          user_name: "BoxUK Automated Package Management"
          user_email: "developers@boxuk.com"

      # with tag
      - name: Split Monorepo with Tag
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@2.3"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: "packages/${{ matrix.packages.local_path }}"
          repository_organization: "boxuk"
          repository_name: "${{ matrix.packages.target_repo }}"
          user_name: "BoxUK Automated Package Management"
          user_email: "developers@boxuk.com"
