name: Update WP Deps

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env: 
  WORDPRESS_VERSION: ${{ vars.WORDPRESS_VERSION }}

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Update
        id: update
        uses: 'boxuk/wp-deps-auto-update@main'
        with:
          WP_VERSION: ${{ env.WORDPRESS_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save PR number
        env:
          PR_NUMBER: ${{ steps.update.outputs.pull-request-number }}
        run: |
            mkdir -p ./pr
            echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
