name: Update WP Deps

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env: 
  WORDPRESS_VERSION: ${{ vars.WORDPRESS_VERSION }}

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Update
        uses: './.github/wp-packages'
        with:
          WP_VERSION: ${{ env.WORDPRESS_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: update-wp-deps/${{ env.WORDPRESS_VERSION }}
          persist-credentials: false
      
      - name: Run JS Tests
        uses: ./.github/workflows/tests-js.yml
      - name: Run PHP Tests
        uses: ./.github/workflows/tests-php.yml
      
           
        